### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by liuyx599** [navis-org/fafbseg-py#12]
when I read the tutorials to fetche the neuron as mesh and then skeletonizes it in https://fafbseg-py.readthedocs.io/en/latest/source/tutorials/flywire_neurons.html, but the program reported an error `OverflowError: Python int too large to convert to C long` ，The code is all from the official website tutorial. I remember a few months ago when I wanted to implement the same code to obtain the skeleton, it was very smooth. I don't know what happened now, and I sincerely request your help

```python
import navis
from fafbseg import flywire
sk = flywire.skeletonize_neuron(720575940617774213, progress=False)
```
```
Skeletonizing: 100%|██████████| 232440/232440 [00:01<00:00, 214595.25it/s]
Traceback (most recent call last):
  File "D:/Codes/230308-point-visualize/0417_get_flywire_swc.py", line 14, in <module>
    sk = flywire.skeletonize_neuron(720575940634710629)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\fafbseg\flywire\skeletonize.py", line 204, in skeletonize_neuron
    if is_materialized_root(id):
  File "C:\Users\Administrator\miniconda3\lib\site-packages\fafbseg\flywire\utils.py", line 388, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\fafbseg\flywire\annotations.py", line 140, in is_materialized_root
    id = make_iterable(id, force_type=int)
  File "C:\Users\Administrator\miniconda3\lib\site-packages\fafbseg\utils.py", line 124, in make_iterable
    return np.asarray(x, dtype=force_type)
OverflowError: Python int too large to convert to C long
```
The same ID was okay when I obtained the mesh
```python
n = flywire.get_mesh_neuron(720575940617774213)
print(n)
```
it succeeded
```
type            navis.MeshNeuron
name                        None
id            720575940617774213
units                1 nanometer
n_vertices                265599
n_faces                   532059
dtype: object
```

**Comment by schlegelp** [comment]
I suspect this is a Windows-specific issue: as far as I know the default integer (`int`) data type is 32bit on Windows as opposed to 64bit on OSX/Linux. The FlyWire root IDs can't be squeezed into 32bit though - which is why it complains. This issue can be resolved by using `numpy.int64` instead of the built-in `int`. I thought I had removed all left-over uses of `int` but apparently forgot the one that caused your issue. 

Just pushed a small commit (a2cccde) that should fix your problem. Unfortunately, I don't have a Windows machine to test though.

Could you please re-install `fafbseg` from Github:
```bash
pip3 uninstall fafbseg -y
pip3 install git+https://github.com/flyconnectome/fafbseg-py.git
```

Then try running the offending code in a **fresh** Python session?

**Comment by schlegelp** [comment]
Assuming this has been fixed. Feel free to re-open if it hasn't.
